# Spring properties
spring:
  application:
    name: reg-service  # Service registers under this name

# HTTP Server
server.port: 1111   # HTTP (Tomcat) port

# Enable actuator access without security checks - DEVELOPMENT ONLY
# Spring Boot 1.5
# management.security.enabled: false
# Spring Boot 2.x
management.endpoints.web.exposure.include: '*'

